
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coffeepy"
version = "0.1.2"
authors = [
  { name="kuvaus", email="kuvaus@users.noreply.github.com" },
]
description = "Coffeepy prevents the system from sleeping"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
coffeepy = "coffeepy.coffeepy:run"

[project.urls]
"Homepage" = "https://github.com/kuvaus/coffeepy"
"Bug Tracker" = "https://github.com/kuvaus/coffeepy/issues"

